# Configurações do Servidor
server.port=8080
spring.application.name=cinesia

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cinesia
spring.datasource.username=postgres
spring.datasource.password=kapri
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de Upload de Arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Diretório para armazenar imagens
app.upload.dir=uploads/images
